CREATE TABLE IF NOT EXISTS task (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    version INTEGER DEFAULT 0,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    complete_date TIMESTAMP,
    promise_date TIMESTAMP,
    priority VARCHAR(50) NOT NULL DEFAULT 'MEDIUM'
);